name = "Psychrometrics"
uuid = "472f9582-ce5d-4ebb-8ee3-e152ac199b96"
authors = ["Alexandre Umpierre (aumpierre@gmail.com)"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
